### ISSUE TITLE
Truffle unbox error

### ISSUE THREAD

**Issue by shivamdawer** [truffle-box/react-auth-box#16]
Hi,

My truffle version is 3.0.5. On running 'truffle unbox react-auth', I get the following :

Downloading...
Error: A Truffle project already exists at the destination. Stopping to prevent overwriting data.
    at /home/shivam/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:206243:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3

Any idea what could be going wrong?

**Comment by shivamdawer** [comment]
The cli.bundled.js file is created by running 
`sudo npm install -g truffle@3.0.5`

**Comment by shivamdawer** [comment]
The error was simple but invisible. There is no need to run `truffle unbox react-auth` if you have already cloned this project.
