### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by LeopoldoD** [truffle-box/react-auth-box#9]
I have just downloaded the React-auth-box and followed all the steps. I'm using testrpc for testing. However, I'm getting the following errors while doing truffle test:
1.  Error: VM Exception while processing transaction: invalid opcode
2. Error: SimpleStorage has not been deployed to detected network (network/artifact mismatch)

I'm getting a similar error while testing the webpack server:
- Error: Authentication has not been deployed to detected network (network/artifact mismatch)

Testrpc appears to be connected to my dApp, but at the end displays the following error:
  Transaction: 0xe54ab4cc933946de26a0176ac25c3a4e79ab752efa006054bdd4b30fb5a74d3f
  Gas usage: 4712388
  Block Number: 76
  Block Time: Thu Jul 13 2017 13:12:02 GMT+0200 (CEST)
  **Runtime Error: invalid opcode**

Any help is appreaciated. Thanks.

Leopoldo.

**Comment by appjitsu** [comment]
Yep. Same here...

Compilation and migration seem to work fine: ie, no errors until you try to browse to the login view or click the signup button.

**Comment by chunkzer** [comment]
Same here. Anywords on workaround or fixes to this issue?

**Comment by inzig** [comment]
Facing same issue Any solution??

**Comment by LeopoldoD** [comment]
have you guys deployed their contracts to the network (testrpc, geth etc.)?
- truffle migrate

**Comment by LeopoldoD** [comment]
Recommendations:
- Check Metamask status (pointing out to port 8545)
- Reset migrations ("truffle migrate --reset")

**Comment by inzig** [comment]
did that.. but still getting the same error,. Tried multiple times now downloaded the Box again and again repeat the process described.

> turffle develop
compile
migrate

but still the same result 
testrpc is running

so is MetaMask

**Comment by LeopoldoD** [comment]
are your contracts deployed to the network? Some lines should appear in testrpc indicating the contracts are successfully deployed.  For example:
  Transaction: 0x7403cc1ce6bb29264732e5d677e8b3c2f96cbba039736ddd14eb9e4a3c09be89
  Contract created: 0x6f9379db54985b6d25da140dd7c41a8d6e50f579
  Gas usage: 160259
  Block Number: 113
  Block Time: Tue Nov 14 2017 10:54:48 GMT+0100 (CET)

eth_newBlockFilter
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
eth_uninstallFilter
eth_sendTransaction

  Transaction: 0x852bcf6d883e9a67edd80c0f20cadd48b1b0d24a166b83ae33aad62c59041bb3
  Contract created: 0xf973bd1e79097099a97602329b73c12cefccb928
  Gas usage: 2322314
  Block Number: 114
  Block Time: Tue Nov 14 2017 10:54:48 GMT+0100 (CET)

eth_newBlockFilter
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
eth_uninstallFilter
eth_sendTransaction

  Transaction: 0x3b8f451221b223d155b9afab59800c0d6018a444dea00371260f9641201ed2dd
  Gas usage: 26798
  Block Number: 115
  Block Time: Tue Nov 14 2017 10:54:48 GMT+0100 (CET)

**Comment by inzig** [comment]
Actually no these are not comming in testrpc

**Comment by LeopoldoD** [comment]
Then your contracts are not deployed to testrpc, therefore, you can not interact with them. 
Make sure Metamask is listening to the same port as testrpc is running (default port 8545).

**Comment by inzig** [comment]
When i use migrate without 
truffle develop

this is the result 

> inzamam@inzamam-Lenovo-ideapad-110-15ISK:~/Documents/truffle-webpack$ truffle migrate --reset
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Error: Exceeds block gas limit
    at StateManager.queueTransaction (/usr/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:84915:21)
    at GethApiDouble.eth_sendTransaction (/usr/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:84423:14)
    at GethApiDouble.handleRequest (/usr/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:84222:10)
    at next (/usr/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:53732:18)
    at GethDefaults.handleRequest (/usr/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:84119:12)
    at next (/usr/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:53732:18)
    at FilterSubprovider.handleRequest (/usr/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:60186:7)
    at next (/usr/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:53732:18)
    at DelayedBlockFilter.handleRequest (/usr/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:83947:3)
    at next (/usr/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:53732:18)
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:331156:36
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:175492:11
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:314196:9
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
    at emitNone (events.js:91:20)

**Comment by LeopoldoD** [comment]
Are you running the standard contracts from truffle box or have you added your own contracts?

**Comment by inzig** [comment]
Standard contracts of truffle Boxes ,. without any editing

**Comment by inzig** [comment]
BTW my testrpc account 0 balance in MetaMask

**Comment by LeopoldoD** [comment]
I have not faced this issue, perhaps review this [link](https://github.com/trufflesuite/truffle/issues/271). Your Metamask balance should be 100 for each testrpc account (by default), try importing a different private key in Metamask.

**Comment by inzig** [comment]
@LeopoldoD  here is the screen shot where i am stuck

[https://ibb.co/kM7n3G](https://ibb.co/kM7n3G)

**Comment by LeopoldoD** [comment]
Ok, you are using the default Metamask account. You need to import a new account:
* From testrpc, copy the first private key. The list of public and private keys are provided when you run testrpc. 
* From Metamask select the man symbol (upper right side).
* Select import account.
* Paste the private key from testrpc.
* A new account should appear showing a balance of 100 ether.

**Comment by nekifirus** [comment]
Same issue. I don't understand why metamask needed. Truffle box. Follow instructions.

**Comment by robertsimoes** [comment]
+1 still struggling with this.

**Comment by ctapang** [comment]
At least in my case, the contracts are being deployed twice. There is an auto-migrate that runs with "truffle test", and it fails. The command "truffle deploy:contracts" works, but the auto-migrate doesn't. So what I did to fix the issue was to modify the migration scripts: before calling deployer.deploy() or <contract>.new(), check first whether that particular contract has already been successfully deployed, and don't deploy again if already deployed. I use <contract>.isDeployed() to determine if it is already deployed, and if so call <contract>.deployed() instead of deployer.deploy().

**Comment by Squall949** [comment]
Hi @nekifirus , for this issue 
> contract.js:419 Uncaught (in promise) Error: Contract has not been deployed to detected network (network/artifact mismatch)

In my case, I found out it was caused by the chrome extension of MetaMask, which resulted in getting wrong network_id. 

After I disabled the extension, the result was correct as expected. [https://github.com/truffle-box/react-box/issues/33](https://github.com/truffle-box/react-box/issues/33)

**Comment by ashok-kumar** [comment]
In my case it solved by updating proper network_id in config files. 

- After starting testrpc, get the network id by using following command.(paste following command in new terminal window)
         `curl -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[]}' http://localhost:8545`
- It will give you following response. Here 'result' will be the network id
          `{"jsonrpc":"2.0","result":"1519215457240"}`
- Update the network id in config files - `truffle.js` or `truffle-config.js`

Credits: [https://ethereum.stackexchange.com](https://ethereum.stackexchange.com/questions/19037/truffle-webpack-starts-with-error-metacoin-has-not-been-deployed-to-detected-ne)

**Comment by JesseAbram** [comment]
Try to run migrate again as migrate --reset '
